# -*- coding: utf-8 -*-
"""backward_chaining

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EiDtqC2JHEaS0QkneSKmMoNvfZhzM2qJ
"""

import pandas as pd

df = pd.read_excel('/content/dataset_umkm.xlsx')
df.head()

# ubah ke kategori (tetap dari kolom asli)
df['aset_kat'] = df['aset'].apply(lambda x: 'Tinggi' if x > df['aset'].mean() else 'Rendah')
df['omset_kat'] = df['omset'].apply(lambda x: 'Tinggi' if x > df['omset'].mean() else 'Rendah')
df['laba_kat'] = df['laba'].apply(lambda x: 'Tinggi' if x > df['laba'].mean() else 'Rendah')
df['pelanggan_kat'] = df['jumlah_pelanggan'].apply(lambda x: 'Banyak' if x > df['jumlah_pelanggan'].mean() else 'Sedikit')

def backward_chaining(row, target):

    # Potensi Tinggi
    if target == 'Tinggi':
        return (
            row['aset_kat'] == 'Tinggi' and
            row['omset_kat'] == 'Tinggi' and
            row['laba_kat'] == 'Tinggi'
        )

    # Potensi Sedang
    elif target == 'Sedang':
        return (
            row['omset_kat'] == 'Tinggi' or
            row['pelanggan_kat'] == 'Banyak'
        )

    # Potensi Rendah
    elif target == 'Rendah':
        return (
            row['aset_kat'] == 'Rendah' and
            row['laba_kat'] == 'Rendah'
        )

    return False

def bc_potensi(row):

    if backward_chaining(row, 'Tinggi'):
        return 'Potensi Tinggi'

    elif backward_chaining(row, 'Sedang'):
        return 'Potensi Sedang'

    else:
        return 'Potensi Rendah'


df['BC_Potensi'] = df.apply(bc_potensi, axis=1)

df[['nama_usaha','daerah','BC_Potensi']].head()

df['BC_Potensi'].value_counts()