# -*- coding: utf-8 -*-
"""Certainty Factor .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KovPiw0o8sjJxdTti2WMQg4TkxVq7Qj_
"""

import pandas as pd
import numpy as np

# Memuat dataset
file_path = '/content/dataset_umkm.xlsx'
df = pd.read_excel(file_path)

# Menampilkan informasi dasar dan 5 baris pertama
print("Informasi Dataset:")
display(df.info())
display(df.head())

"""### Implementasi Certainty Factor (CF)

Metode Certainty Factor biasanya memerlukan nilai keyakinan pakar (*Measure of Belief* - MB) dan ketidakyakinan (*Measure of Disbelief* - MD) untuk setiap kriteria atau gejala. Rumus dasarnya adalah:

$CF[h,e] = MB[h,e] - MD[h,e]$

Dan untuk kombinasi beberapa kriteria:
$CF_{combine}(CF_1, CF_2) = CF_1 + CF_2 \times (1 - CF_1)$ (jika keduanya positif).

Setelah kita melihat data di atas, kita akan menentukan kolom mana yang menjadi kriteria dan bagaimana memberikan bobot CF-nya.
"""

def calculate_cf(row):
    # Kriteria 1: Margin Laba Positif (MB=0.6, MD=0.1)
    cf1 = 0.5 if row['margin_laba'] > 0 else -0.3

    # Kriteria 2: ROA > 10% (MB=0.7, MD=0.2)
    cf2 = 0.5 if row['roa'] > 10 else -0.2

    # Kriteria 3: Utilisasi Produksi Tinggi (>500000) (MB=0.4, MD=0.1)
    cf3 = 0.3 if row['utilisasi_produksi'] > 500000 else -0.1

    # Kombinasi CF (CF1 dan CF2)
    if cf1 >= 0 and cf2 >= 0:
        cf_combined = cf1 + cf2 * (1 - cf1)
    elif cf1 < 0 and cf2 < 0:
        cf_combined = cf1 + cf2 * (1 + cf1)
    else:
        cf_combined = (cf1 + cf2) / (1 - min(abs(cf1), abs(cf2)))

    # Kombinasi dengan CF3
    if cf_combined >= 0 and cf3 >= 0:
        cf_final = cf_combined + cf3 * (1 - cf_combined)
    elif cf_combined < 0 and cf3 < 0:
        cf_final = cf_combined + cf3 * (1 + cf_combined)
    else:
        cf_final = (cf_combined + cf3) / (1 - min(abs(cf_combined), abs(cf3)))

    return cf_final

# Terapkan fungsi ke dataframe
df['certainty_factor'] = df.apply(calculate_cf, axis=1)

# Urutkan berdasarkan CF tertinggi (UMKM paling potensial/sukses)
result = df[['nama_usaha', 'jenis_usaha', 'margin_laba', 'roa', 'certainty_factor']].sort_values(by='certainty_factor', ascending=False)

print("Hasil Pemodelan Certainty Factor (Top 10 UMKM):")
display(result.head(10))

"""### Penjelasan Kode Pemodelan Certainty Factor (CF)

Kode di atas melakukan penilaian otomatis terhadap kelayakan UMKM dengan langkah-langkah berikut:

1. **Definisi Kriteria (Evidence):**
   - **Kriteria 1 (Margin Laba):** Jika positif, diberikan nilai kepastian 0.5. Jika negatif, diberikan nilai penalti -0.3.
   - **Kriteria 2 (ROA):** Jika di atas 10%, dianggap sehat (0.5), jika di bawah dianggap kurang (-0.2).
   - **Kriteria 3 (Utilisasi):** Jika volume produksi tinggi, menambah keyakinan sebesar 0.3, jika rendah mengurangi -0.1.

2. **Logika Kombinasi CF:**
   Metode ini menggunakan rumus standar CF untuk menggabungkan beberapa bukti:
   - **Jika keduanya positif:** $CF_{total} = CF_1 + CF_2 \times (1 - CF_1)$. Ini memperkuat nilai keyakinan.
   - **Jika keduanya negatif:** $CF_{total} = CF_1 + CF_2 \times (1 + CF_1)$. Ini memperkuat nilai ketidakyakinan.
   - **Jika berlawanan:** Digunakan rumus normalisasi $(CF_1 + CF_2) / (1 - \min(|CF_1|, |CF_2|))$ untuk mencari selisih bersihnya.

3. **Proses Batch (Apply):**
   - `df.apply(calculate_cf, axis=1)` menjalankan fungsi tersebut untuk seluruh 13.000+ baris data secara efisien.

4. **Perankingan:**
   - Data diurutkan berdasarkan `certainty_factor` secara *descending* (dari yang terbesar ke terkecil) untuk mengidentifikasi UMKM yang paling memenuhi kriteria kesuksesan bisnis.

### Perbandingan Akademis: Certainty Factor vs Metode Sistem Pakar Lainnya

Berikut adalah perbandingan antara **Certainty Factor (CF)** denganmetode lainnya:

| Fitur Perbandingan | Certainty Factor (CF) | Forward Chaining | Backward Chaining | Teorema Bayes |
|---|---|---|---|---|
| **Logika Dasar** | Heuristik (MB - MD) | Data-driven (If-Then) | Goal-driven (If-Then) | Probabilitas Statistik |
| **Penanganan Ketidakpastian** | Sangat Baik (Skala -1 s/d 1) | Terbatas (Biner: Ya/Tidak) | Terbatas (Biner: Ya/Tidak) | Sangat Baik (P(H|E)) |
| **Arah Pencarian** | Kombinasi Bukti | Dari Fakta ke Kesimpulan | Dari Target ke Fakta | Kondisional Probabilitas |
| **Kebutuhan Data** | Bobot Pakar (Subjektif) | Aturan/Rules | Aturan/Rules | Data Historis (Objektif) |

#### Analisis Setiap Metode:

1. **VS Forward Chaining:**
   Forward Chaining cocok jika kita ingin melakukan navigasi dari data yang ada untuk menemukan semua kemungkinan hasil. Namun, Forward Chaining murni bersifat biner. Jika data UMKM Anda memiliki 'noise' atau nilai yang tidak pasti, CF lebih unggul karena dapat memberikan derajat keyakinan, bukan sekadar 'Lolos' atau 'Tidak Lolos'.

2. **VS Backward Chaining:**
   Backward Chaining bekerja terbalik, mulai dari hipotesis (misal: 'Apakah UMKM ini layak investasi?') lalu mencari bukti pendukung. Ini kurang efisien untuk dataset besar seperti UMKM Anda (13rb+ baris) karena mesin harus melakukan pembuktian satu per satu untuk setiap baris data, sedangkan CF bisa diproses secara batch (vektorisasi).

3. **VS Teorema Bayes:**
   Bayes adalah pesaing terberat CF. Bayes bersifat objektif karena berbasis frekuensi data historis. Namun, Bayes membutuhkan nilai probabilitas prior yang akurat. Jika data historis Anda tidak memiliki label 'hasil akhir' yang pasti, Teorema Bayes akan sulit diimplementasikan, sehingga CF (yang berbasis pengetahuan pakar) menjadi lebih praktis.

### Kesimpulan: Mana yang Paling Cocok?

Untuk **Dataset UMKM** ini:
* **Pilihan Utama (Jika ada Pakar): Certainty Factor.** Karena kita bisa langsung memetakan indikator bisnis (ROA, Margin) ke dalam nilai keyakinan tanpa harus memiliki data label sukses/gagal di masa lalu.
* **Pilihan Utama (Jika ada Label Data): Teorema Bayes.** Jika dataset memiliki kolom target (misal: Status Keberlanjutan), Teorema Bayes akan memberikan hasil yang lebih akurat secara statistik dibandingkan CF yang subjektif.
* **Kurang Cocok: Forward/Backward Chaining.** Karena data UMKM bersifat kontinu (angka) dan penuh ketidakpastian, sehingga logika biner kaku dari Chaining akan membuang banyak informasi penting.
"""

